spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurants
    username: postgres
    password: choupinou
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

jwt:
  secret: "votre_secret"
  expiration: 86400000